Proyecto/Album/src/java/JSF/UserController.java
package JSF;

import Entities.User;
import JSF.util.JsfUtil;
import JSF.util.JsfUtil.PersistAction;
import Session.UserFacade;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@ManagedBean(name = "userController")
@SessionScoped
public class UserController implements Serializable {

    @EJB
    private Session.UserFacade ejbFacade;
    private List<User> items = null;
    private User selected;

    public UserController() {
    }

    public User getSelected() {
        return selected;
    }

    public void setSelected(User selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private UserFacade getFacade() {
        return ejbFacade;
    }

    public User prepareCreate() {
        selected = new User();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/Bundle").getString("UserCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/Bundle").getString("UserUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/Bundle").getString("UserDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<User> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/Bundle").getString("PersistenceErrorOccured"));
            }
        }
    }

    public List<User> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<User> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = User.class)
    public static class UserControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            UserController controller = (UserController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "userController");
            return controller.getFacade().find(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof User) {
                User o = (User) object;
                return getStringKey(o.getIdUser());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), User.class.getName()});
                return null;
            }
        }

    }

}

Proyecto/Album/web/user/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="UserCreateDlg" widgetVar="UserCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.CreateUserTitle}">
            <h:form id="UserCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{userController.selected != null}">
                        <p:outputLabel value="#{bundle.CreateUserLabel_name}" for="name" />
                        <p:inputText id="name" value="#{userController.selected.name}" title="#{bundle.CreateUserTitle_name}" required="true" requiredMessage="#{bundle.CreateUserRequiredMessage_name}"/>
                        <p:outputLabel value="#{bundle.CreateUserLabel_lastname}" for="lastname" />
                        <p:inputText id="lastname" value="#{userController.selected.lastname}" title="#{bundle.CreateUserTitle_lastname}" required="true" requiredMessage="#{bundle.CreateUserRequiredMessage_lastname}"/>
                        <p:outputLabel value="#{bundle.CreateUserLabel_age}" for="age" />
                        <p:inputText id="age" value="#{userController.selected.age}" title="#{bundle.CreateUserTitle_age}" required="true" requiredMessage="#{bundle.CreateUserRequiredMessage_age}"/>
                        <p:outputLabel value="#{bundle.CreateUserLabel_login}" for="login" />
                        <p:inputText id="login" value="#{userController.selected.login}" title="#{bundle.CreateUserTitle_login}" required="true" requiredMessage="#{bundle.CreateUserRequiredMessage_login}"/>
                        <p:outputLabel value="#{bundle.CreateUserLabel_password}" for="password" />
                        <p:inputText id="password" value="#{userController.selected.password}" title="#{bundle.CreateUserTitle_password}" required="true" requiredMessage="#{bundle.CreateUserRequiredMessage_password}"/>
                        <p:outputLabel value="#{bundle.CreateUserLabel_phone}" for="phone" />
                        <p:inputText id="phone" value="#{userController.selected.phone}" title="#{bundle.CreateUserTitle_phone}" required="true" requiredMessage="#{bundle.CreateUserRequiredMessage_phone}"/>
                        <p:outputLabel value="#{bundle.CreateUserLabel_urlPicture}" for="urlPicture" />
                        <p:inputText id="urlPicture" value="#{userController.selected.urlPicture}" title="#{bundle.CreateUserTitle_urlPicture}" required="true" requiredMessage="#{bundle.CreateUserRequiredMessage_urlPicture}"/>
                        <p:outputLabel value="#{bundle.CreateUserLabel_address}" for="address" />
                        <p:inputText id="address" value="#{userController.selected.address}" title="#{bundle.CreateUserTitle_address}" required="true" requiredMessage="#{bundle.CreateUserRequiredMessage_address}"/>
                        <p:outputLabel value="#{bundle.CreateUserLabel_email}" for="email" />
                        <p:inputText id="email" value="#{userController.selected.email}" title="#{bundle.CreateUserTitle_email}" required="true" requiredMessage="#{bundle.CreateUserRequiredMessage_email}"/>
                        <p:outputLabel value="#{bundle.CreateUserLabel_idAccessLevel}" for="idAccessLevel" />
                        <p:selectOneMenu id="idAccessLevel" value="#{userController.selected.idAccessLevel}" required="true" requiredMessage="#{bundle.EditUserRequiredMessage_idAccessLevel}">
                            <f:selectItems value="#{accesslevelController.itemsAvailableSelectOne}"
                                           var="idAccessLevelItem"
                                           itemValue="#{idAccessLevelItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.CreateUserLabel_idRelationship}" for="idRelationship" />
                        <p:selectOneMenu id="idRelationship" value="#{userController.selected.idRelationship}" required="true" requiredMessage="#{bundle.EditUserRequiredMessage_idRelationship}">
                            <f:selectItems value="#{relationshipController.itemsAvailableSelectOne}"
                                           var="idRelationshipItem"
                                           itemValue="#{idRelationshipItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{userController.create}" value="#{bundle.Save}" update="display,:UserListForm:datalist,:growl" oncomplete="handleSubmit(args,'UserCreateDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="UserCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

Proyecto/Album/web/user/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="UserEditDlg" widgetVar="UserEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.EditUserTitle}">
            <h:form id="UserEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{userController.selected != null}">
                        <p:outputLabel value="#{bundle.EditUserLabel_idUser}" for="idUser" />
                        <p:inputText id="idUser" value="#{userController.selected.idUser}" title="#{bundle.EditUserTitle_idUser}" required="true" requiredMessage="#{bundle.EditUserRequiredMessage_idUser}" disabled="true"/>
                        <p:outputLabel value="#{bundle.EditUserLabel_name}" for="name" />
                        <p:inputText id="name" value="#{userController.selected.name}" title="#{bundle.EditUserTitle_name}" required="true" requiredMessage="#{bundle.EditUserRequiredMessage_name}"/>
                        <p:outputLabel value="#{bundle.EditUserLabel_lastname}" for="lastname" />
                        <p:inputText id="lastname" value="#{userController.selected.lastname}" title="#{bundle.EditUserTitle_lastname}" required="true" requiredMessage="#{bundle.EditUserRequiredMessage_lastname}"/>
                        <p:outputLabel value="#{bundle.EditUserLabel_age}" for="age" />
                        <p:inputText id="age" value="#{userController.selected.age}" title="#{bundle.EditUserTitle_age}" required="true" requiredMessage="#{bundle.EditUserRequiredMessage_age}"/>
                        <p:outputLabel value="#{bundle.EditUserLabel_login}" for="login" />
                        <p:inputText id="login" value="#{userController.selected.login}" title="#{bundle.EditUserTitle_login}" required="true" requiredMessage="#{bundle.EditUserRequiredMessage_login}"/>
                        <p:outputLabel value="#{bundle.EditUserLabel_password}" for="password" />
                        <p:inputText id="password" value="#{userController.selected.password}" title="#{bundle.EditUserTitle_password}" required="true" requiredMessage="#{bundle.EditUserRequiredMessage_password}"/>
                        <p:outputLabel value="#{bundle.EditUserLabel_phone}" for="phone" />
                        <p:inputText id="phone" value="#{userController.selected.phone}" title="#{bundle.EditUserTitle_phone}" required="true" requiredMessage="#{bundle.EditUserRequiredMessage_phone}"/>
                        <p:outputLabel value="#{bundle.EditUserLabel_urlPicture}" for="urlPicture" />
                        <p:inputText id="urlPicture" value="#{userController.selected.urlPicture}" title="#{bundle.EditUserTitle_urlPicture}" required="true" requiredMessage="#{bundle.EditUserRequiredMessage_urlPicture}"/>
                        <p:outputLabel value="#{bundle.EditUserLabel_address}" for="address" />
                        <p:inputText id="address" value="#{userController.selected.address}" title="#{bundle.EditUserTitle_address}" required="true" requiredMessage="#{bundle.EditUserRequiredMessage_address}"/>
                        <p:outputLabel value="#{bundle.EditUserLabel_email}" for="email" />
                        <p:inputText id="email" value="#{userController.selected.email}" title="#{bundle.EditUserTitle_email}" required="true" requiredMessage="#{bundle.EditUserRequiredMessage_email}"/>
                        <p:outputLabel value="#{bundle.EditUserLabel_idAccessLevel}" for="idAccessLevel" />
                        <p:selectOneMenu id="idAccessLevel" value="#{userController.selected.idAccessLevel}" required="true" requiredMessage="#{bundle.EditUserRequiredMessage_idAccessLevel}">
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{accesslevelController.itemsAvailableSelectOne}"
                                           var="idAccessLevelItem"
                                           itemValue="#{idAccessLevelItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{bundle.EditUserLabel_idRelationship}" for="idRelationship" />
                        <p:selectOneMenu id="idRelationship" value="#{userController.selected.idRelationship}" required="true" requiredMessage="#{bundle.EditUserRequiredMessage_idRelationship}">
                            <f:selectItem itemLabel="#{bundle.SelectOneMessage}"/>
                            <f:selectItems value="#{relationshipController.itemsAvailableSelectOne}"
                                           var="idRelationshipItem"
                                           itemValue="#{idRelationshipItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{userController.update}" value="#{bundle.Save}" update="display,:UserListForm:datalist,:growl" oncomplete="handleSubmit(args, 'UserEditDialog');"/>
                    <p:commandButton value="#{bundle.Cancel}" onclick="UserEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

Proyecto/Album/web/user/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListUserTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="UserListForm">
                <p:panel header="#{bundle.ListUserTitle}">
                    <p:dataTable id="datalist" value="#{userController.items}" var="item"
                                 selectionMode="single" selection="#{userController.selected}"
                                 paginator="true"
                                 rowKey="#{item.idUser}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUserTitle_idUser}"/>
                            </f:facet>
                            <h:outputText value="#{item.idUser}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUserTitle_name}"/>
                            </f:facet>
                            <h:outputText value="#{item.name}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUserTitle_lastname}"/>
                            </f:facet>
                            <h:outputText value="#{item.lastname}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUserTitle_age}"/>
                            </f:facet>
                            <h:outputText value="#{item.age}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUserTitle_login}"/>
                            </f:facet>
                            <h:outputText value="#{item.login}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUserTitle_password}"/>
                            </f:facet>
                            <h:outputText value="#{item.password}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUserTitle_phone}"/>
                            </f:facet>
                            <h:outputText value="#{item.phone}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUserTitle_urlPicture}"/>
                            </f:facet>
                            <h:outputText value="#{item.urlPicture}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUserTitle_address}"/>
                            </f:facet>
                            <h:outputText value="#{item.address}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUserTitle_email}"/>
                            </f:facet>
                            <h:outputText value="#{item.email}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="Nivel de acceso"/>
                            </f:facet>
                            <h:outputText value="#{item.idAccessLevel.name}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="Parentesco Familiar"/>
                            </f:facet>
                            <h:outputText value="#{item.idRelationship.description}  de Miguel"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="createButton" icon="ui-icon-plus"   value="#{bundle.Create}" actionListener="#{userController.prepareCreate}" update=":UserCreateForm" oncomplete="PF('UserCreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle.View}" update=":UserViewForm" oncomplete="PF('UserViewDialog').show()" disabled="#{empty userController.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{bundle.Edit}" update=":UserEditForm" oncomplete="PF('UserEditDialog').show()" disabled="#{empty userController.selected}"/>
                            <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{bundle.Delete}" actionListener="#{userController.destroy}" update=":growl,datalist" disabled="#{empty userController.selected}"/>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

Proyecto/Album/web/user/List_1.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/template2.xhtml">


        <ui:define name="title">
            <h:outputText value="#{bundle.ListUserTitle}"></h:outputText>
        </ui:define>

        <ui:define name="body">
            <h:form id="UserListForm">
                <p:panel header="#{bundle.ListUserTitle}">
                    <p:dataTable id="datalist" value="#{userController.items}" var="item"
                                 selectionMode="single" selection="#{userController.selected}"
                                 paginator="true"
                                 rowKey="#{item.idUser}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update=" viewButton  "/>
                        <p:ajax event="rowUnselect" update=" viewButton  "/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUserTitle_idUser}"/>
                            </f:facet>
                            <h:outputText value="#{item.idUser}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUserTitle_name}"/>
                            </f:facet>
                            <h:outputText value="#{item.name}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUserTitle_lastname}"/>
                            </f:facet>
                            <h:outputText value="#{item.lastname}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUserTitle_age}"/>
                            </f:facet>
                            <h:outputText value="#{item.age}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUserTitle_phone}"/>
                            </f:facet>
                            <h:outputText value="#{item.phone}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUserTitle_urlPicture}"/>
                            </f:facet>
                            <h:outputText value="#{item.urlPicture}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUserTitle_address}"/>
                            </f:facet>
                            <h:outputText value="#{item.address}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUserTitle_email}"/>
                            </f:facet>
                            <h:outputText value="#{item.email}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUserTitle_idAccessLevel}"/>
                            </f:facet>
                            <h:outputText value="#{item.idAccessLevel.name}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListUserTitle_idRelationship}"/>
                            </f:facet>
                            <h:outputText value="#{item.idRelationship.description}"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{bundle.View}" update=":UserViewForm" oncomplete="PF('UserViewDialog').show()" disabled="#{empty userController.selected}"/>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>
            <ui:include src="View_1.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

Proyecto/Album/web/user/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="UserViewDlg" widgetVar="UserViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{bundle.ViewUserTitle}">
            <h:form id="UserViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{userController.selected != null}">
                        <h:outputText value="#{bundle.ViewUserLabel_idUser}"/>
                        <h:outputText value="#{userController.selected.idUser}" title="#{bundle.ViewUserTitle_idUser}"/>
                        <h:outputText value="#{bundle.ViewUserLabel_name}"/>
                        <h:outputText value="#{userController.selected.name}" title="#{bundle.ViewUserTitle_name}"/>
                        <h:outputText value="#{bundle.ViewUserLabel_lastname}"/>
                        <h:outputText value="#{userController.selected.lastname}" title="#{bundle.ViewUserTitle_lastname}"/>
                        <h:outputText value="#{bundle.ViewUserLabel_age}"/>
                        <h:outputText value="#{userController.selected.age}" title="#{bundle.ViewUserTitle_age}"/>
                        <h:outputText value="#{bundle.ViewUserLabel_login}"/>
                        <h:outputText value="#{userController.selected.login}" title="#{bundle.ViewUserTitle_login}"/>
                        <h:outputText value="#{bundle.ViewUserLabel_password}"/>
                        <h:outputText value="#{userController.selected.password}" title="#{bundle.ViewUserTitle_password}"/>
                        <h:outputText value="#{bundle.ViewUserLabel_phone}"/>
                        <h:outputText value="#{userController.selected.phone}" title="#{bundle.ViewUserTitle_phone}"/>
                        <h:outputText value="#{bundle.ViewUserLabel_urlPicture}"/>
                        <h:outputText value="#{userController.selected.urlPicture}" title="#{bundle.ViewUserTitle_urlPicture}"/>
                        <h:outputText value="#{bundle.ViewUserLabel_address}"/>
                        <h:outputText value="#{userController.selected.address}" title="#{bundle.ViewUserTitle_address}"/>
                        <h:outputText value="#{bundle.ViewUserLabel_email}"/>
                        <h:outputText value="#{userController.selected.email}" title="#{bundle.ViewUserTitle_email}"/>
                        <h:outputText value="#{bundle.ViewUserLabel_idAccessLevel}"/>
                        <h:outputText value="#{userController.selected.idAccessLevel}" title="#{bundle.ViewUserTitle_idAccessLevel}"/>
                        <h:outputText value="#{bundle.ViewUserLabel_idRelationship}"/>
                        <h:outputText value="#{userController.selected.idRelationship}" title="#{bundle.ViewUserTitle_idRelationship}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{bundle.Close}" onclick="UserViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>